### ISSUE TITLE
ParseError: Unexpected token '<' at 1:1 in https://hastebin.com/documents

### ISSUE THREAD

**Issue by sinjs** [rahatarmanahmed/hastebin#7]
When testing your program by running
```bash
echo "test" | hastebin
```
I am getting this error:
```js
(node:24913) UnhandledPromiseRejectionWarning: ParseError: Unexpected token '<' at 1:1 in https://hastebin.com/documents
<!DOCTYPE html>
^
    at /usr/lib/node_modules/hastebin/node_modules/got/index.js:120:14
    at BufferStream.<anonymous> (/usr/lib/node_modules/hastebin/node_modules/read-all-stream/index.js:64:3)
    at BufferStream.emit (events.js:327:22)
    at finishMaybe (/usr/lib/node_modules/hastebin/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at afterWrite (/usr/lib/node_modules/hastebin/node_modules/readable-stream/lib/_stream_writable.js:492:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:24913) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24913) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The same via the node api

**Comment by rahatarmanahmed** [comment]
That's unfortunate. Maybe the hastebin API changed. I'm not actively
maintaining this anymore so contributions are welcome.
